/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class model_MyNativeLibrary */

#ifndef _Included_model_MyNativeLibrary
#define _Included_model_MyNativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     model_MyNativeLibrary
 * Method:    updateTrailValues
 * Signature: ([DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_model_MyNativeLibrary_updateTrailValues
  (JNIEnv *, jclass, jdoubleArray, jdouble);

/*
 * Class:     model_MyNativeLibrary
 * Method:    calculateParabola
 * Signature: (DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_model_MyNativeLibrary_calculateParabola
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     model_MyNativeLibrary
 * Method:    divRoundAwayFromZero
 * Signature: (DD)I
 */
JNIEXPORT jint JNICALL Java_model_MyNativeLibrary_divRoundAwayFromZero
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     model_MyNativeLibrary
 * Method:    asmAbs
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_model_MyNativeLibrary_asmAbs
  (JNIEnv *, jclass, jint);

/*
 * Class:     model_MyNativeLibrary
 * Method:    sin
 * Signature: (DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_model_MyNativeLibrary_sin
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     model_MyNativeLibrary
 * Method:    isBetween
 * Signature: (DDD)Z
 */
JNIEXPORT jboolean JNICALL Java_model_MyNativeLibrary_isBetween
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     model_MyNativeLibrary
 * Method:    makeInBound
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_model_MyNativeLibrary_makeInBound
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     model_MyNativeLibrary
 * Method:    myHypot
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_model_MyNativeLibrary_myHypot
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     model_MyNativeLibrary
 * Method:    makeRandomMovement
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_model_MyNativeLibrary_makeRandomMovement
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
